Rails.application.config.assets.precompile += %w( video-js.css )
Rails.application.config.assets.precompile += %w( video.js )
#Rails.application.config.assets.precompile += %w( video-js.swf )
Rails.application.config.assets.precompile += %w( youtube.js )
Rails.application.config.assets.precompile += %w( media.vimeo.js )
